/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package New_Desain;

import project_s2_3.*;

/**
 *
 * @author USER
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/logo_baru-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/bthome-removebg-preview.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        suplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/btsuplier-removebg-preview.png"))); // NOI18N
        suplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suplierMouseClicked(evt);
            }
        });
        getContentPane().add(suplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/btlogout-removebg-preview.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        petugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/btmember-removebg-preview.png"))); // NOI18N
        petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petugasMouseClicked(evt);
            }
        });
        getContentPane().add(petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/HOME (1).png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        lpjual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/lp_jual-removebg-preview.png"))); // NOI18N
        lpjual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpjualMouseClicked(evt);
            }
        });
        getContentPane().add(lpjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, -1));

        retur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/retur-removebg-preview (1).png"))); // NOI18N
        retur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returMouseClicked(evt);
            }
        });
        getContentPane().add(retur, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, -1, -1));

        promo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/promo-removebg-preview.png"))); // NOI18N
        promo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                promoMouseClicked(evt);
            }
        });
        getContentPane().add(promo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, -1, -1));

        lpbeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/lp_beli-removebg-preview.png"))); // NOI18N
        lpbeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpbeliMouseClicked(evt);
            }
        });
        getContentPane().add(lpbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        pengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/tr_kluar-removebg-preview.png"))); // NOI18N
        pengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengeluaranMouseClicked(evt);
            }
        });
        getContentPane().add(pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, -1, -1));

        jual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/tr_jual-removebg-preview.png"))); // NOI18N
        jual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jualMouseClicked(evt);
            }
        });
        getContentPane().add(jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, -1, -1));

        beli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/tr_beli-removebg-preview.png"))); // NOI18N
        beli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beliMouseClicked(evt);
            }
        });
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        lpkluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/Frame_117__1_-removebg-preview.png"))); // NOI18N
        lpkluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpkluarMouseClicked(evt);
            }
        });
        getContentPane().add(lpkluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, -1, -1));

        barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desain/dtbarang-removebg-preview.png"))); // NOI18N
        barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangMouseClicked(evt);
            }
        });
        getContentPane().add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain_baru/DESAIN BARU/tengah.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain_baru/DESAIN BARU/sebelahkiri.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain_baru/DESAIN BARU/latar2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain_baru/DESAIN BARU/latar1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
this.setVisible(false);
new Home().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void suplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suplierMouseClicked
this.setVisible(false);
new Suplier().setVisible(true);
//new Suplier().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_suplierMouseClicked

    private void petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasMouseClicked
this.setVisible(false);
new Petugas().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_petugasMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
this.setVisible(false);
new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void beliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beliMouseClicked
this.setVisible(false);
new Transaksi_Beli().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_beliMouseClicked

    private void jualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jualMouseClicked
this.setVisible(false);
new Transaksi_Jual().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jualMouseClicked

    private void pengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengeluaranMouseClicked
this.setVisible(false);
new Pengeluaran().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pengeluaranMouseClicked

    private void barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangMouseClicked
this.setVisible(false);
new Barang().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_barangMouseClicked

    private void promoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promoMouseClicked
this.setVisible(false);
new Promo().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_promoMouseClicked

    private void returMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returMouseClicked
this.setVisible(false);
new Retur().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_returMouseClicked

    private void lpbeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpbeliMouseClicked
this.setVisible(false);
new Laporan_Beli().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lpbeliMouseClicked

    private void lpjualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpjualMouseClicked
this.setVisible(false);
new Laporan_Jual().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lpjualMouseClicked

    private void lpkluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpkluarMouseClicked
this.setVisible(false);
new Laporan_Pengeluaran().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lpkluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel barang = new javax.swing.JLabel();
    public static final javax.swing.JLabel beli = new javax.swing.JLabel();
    public static final javax.swing.JLabel home = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static final javax.swing.JLabel jual = new javax.swing.JLabel();
    public static final javax.swing.JLabel logout = new javax.swing.JLabel();
    public static final javax.swing.JLabel lpbeli = new javax.swing.JLabel();
    public static final javax.swing.JLabel lpjual = new javax.swing.JLabel();
    public static final javax.swing.JLabel lpkluar = new javax.swing.JLabel();
    public static final javax.swing.JLabel pengeluaran = new javax.swing.JLabel();
    public static final javax.swing.JLabel petugas = new javax.swing.JLabel();
    public static final javax.swing.JLabel promo = new javax.swing.JLabel();
    public static final javax.swing.JLabel retur = new javax.swing.JLabel();
    public static final javax.swing.JLabel suplier = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
