/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package New_Desain;

import java.awt.Color;
import java.awt.Menu;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.MenuListener;
import javax.swing.table.DefaultTableModel;/**
 *
 * @author USER
 */
public class Petugas extends javax.swing.JFrame {

    /** Creates new form Petugas */
    public Petugas() {
        initComponents();
        datatable();
        tampil_combobox();
    }

        public void kosongkanfield(){
idpetugas.setText(null);
nmpetugas.setText(null) ;
jabatan.setSelectedItem(null);
nohp.setText(null);
password.setText(null) ;
alamat.setText(null);
gaji.setText(null);
    }
          public void tampil_combobox(){
    try{
        String sql = "Select * from petugas";
        java.sql.Connection conn = (Connection)New_Desain.SKP.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        while(rs.next()){
            jabatan.addItem(rs.getString("Jabatan"));
        }
        rs.last();
        int jumlahdata = rs.getRow();
        rs.first();
    }catch(Exception e){
    }
    }
    public void datatable(){
    DefaultTableModel tbl=new DefaultTableModel();
    tbl.addColumn("ID Petugas");
    tbl.addColumn("Nama Petugas");
    tbl.addColumn("Jabatan");
    tbl.addColumn("Gaji");
    tbl.addColumn("Alamat");
    tbl.addColumn("No HP");
    tbl.addColumn("Password");
    tabel.setModel(tbl);
    try{
        int no=1;
        String sql = "SELECT * FROM petugas ORDER BY Id_Petugas DESC; ";
        java.sql.Connection conn=(Connection)New_Desain.SKP.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next())
        {
            tbl.addRow(new Object[]{
                res.getString("Id_Petugas"),
                res.getString("Nama_Petugas"),
                res.getString("Jabatan"),
                res.getString("Gaji"),
                res.getString("Alamat"),
                res.getString("No_Hp"),
                res.getString("Password"),
            });
                    tabel.setModel(tbl);
    }
}catch (Exception e){
    JOptionPane.showMessageDialog(rootPane, "salah");
}
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idpetugas = new javax.swing.JTextField();
        nmpetugas = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        gaji = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jabatan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(idpetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 230, 30));
        getContentPane().add(nmpetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 230, 30));
        getContentPane().add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 230, 30));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 230, 30));
        getContentPane().add(gaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 230, 30));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 230, 30));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 770, 210));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jButton2.setText("Simpan");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, 120, 40));

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 120, 40));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jButton1.setText("Hapus");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 250, 120, 40));

        getContentPane().add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/logo_baru-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/home-removebg-preview.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/Frame_159__1_-removebg-preview.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/Frame_159__2_-removebg-preview.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/LOGOUT-removebg-preview.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/petugas.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultTableModel tbl=new DefaultTableModel();

        String Id_Petugas = idpetugas.getText();
        String Nama_Petugas = nmpetugas.getText() ;
        String Jabatan = (String) jabatan.getSelectedItem();
        String Gaji = gaji.getText();
        String Alamat = alamat.getText();
        String No_Hp = nohp.getText();
        String Password = password.getText();
        try{
            java.sql.Connection conn=(Connection)New_Desain.SKP.configDB();
            String sql = "INSERT INTO petugas VALUES ('" + Id_Petugas + "','" + Nama_Petugas + "','" + Jabatan + "','"
            + Gaji + "','" + Alamat + "','" + No_Hp + "','" + Password + "')";

            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute(sql);

            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan");
        }
        datatable(); 
kosongkanfield();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            String sql = "UPDATE petugas SET Nama_Petugas='" + nmpetugas.getText() + "' ,Jabatan='" + jabatan.getSelectedItem()+ "' ,Gaji='" + gaji.getText() + "' ,Alamat='"
            + alamat.getText() + "' ,No_Hp='" + nohp.getText() + "' ,Password='" + password.getText()+ "'WHERE Id_Petugas = '"+idpetugas.getText()+"'";
            java.sql.Connection conn = (Connection)New_Desain.SKP.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute(sql);

            JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal "
                + e.getMessage());
        }

        datatable();  
        kosongkanfield();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String ID_Petugas = idpetugas.getText();
        try {
            java.sql.Connection conn=(Connection)New_Desain.SKP.configDB();
            String sql = ("DELETE FROM petugas where Id_Petugas=('" + ID_Petugas + "');");

            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute(sql);

            String Id_Petugas = idpetugas.getText();
            String Nama_Petugas = nmpetugas.getText() ;
            String Jabatan = (String) jabatan.getSelectedItem();
            String Gaji = nohp.getText();
            String Alamat = alamat.getText();
            String No_Hp = nohp.getText();
            String Password = password.getText();

            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        datatable();  
        kosongkanfield();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int baris = tabel.rowAtPoint(evt.getPoint());

        String idptgs = tabel.getValueAt(baris, 0).toString();
        idpetugas.setText(idptgs);

        String Nmptgs = tabel.getValueAt(baris, 1).toString();
        nmpetugas.setText(Nmptgs);

        String Jabatan = tabel.getValueAt(baris, 2).toString();
        jabatan.setSelectedItem(Jabatan);

        String Nohp = tabel.getValueAt(baris, 5).toString();
        nohp.setText(Nohp);

        String Password = tabel.getValueAt(baris, 6).toString();
        password.setText(Password);

        String Alamat = tabel.getValueAt(baris, 4).toString();
        alamat.setText(Alamat);  
        
        String Gaji = tabel.getValueAt(baris, 3).toString();
        gaji.setText(Gaji); // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.setVisible(false);
        new Home().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.setVisible(false);
        new Suplier().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setVisible(false);
        new Petugas().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setVisible(false);
        new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField gaji;
    private javax.swing.JTextField idpetugas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jabatan;
    private javax.swing.JTextField nmpetugas;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField password;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

}
