/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_s2_3;

/**
 *
 * @author ACER
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 63, 107));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo SKPP Dash.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SKP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sistem Kasir Pintar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, -1));

        homee.setBackground(new java.awt.Color(165, 165, 230));
        homee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeeMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 32)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(12, 66, 121));
        jLabel16.setText("Home");

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Homee dash (1).png"))); // NOI18N

        javax.swing.GroupLayout homeeLayout = new javax.swing.GroupLayout(homee);
        homee.setLayout(homeeLayout);
        homeeLayout.setHorizontalGroup(
            homeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeeLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        homeeLayout.setVerticalGroup(
            homeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel1.add(homee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, 50));

        petugas.setBackground(new java.awt.Color(165, 165, 230));
        petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petugasMouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(12, 66, 121));
        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 32)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(12, 66, 121));
        jLabel17.setText("Petugas");

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Profileee (1).png"))); // NOI18N

        javax.swing.GroupLayout petugasLayout = new javax.swing.GroupLayout(petugas);
        petugas.setLayout(petugasLayout);
        petugasLayout.setHorizontalGroup(
            petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, petugasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18))
        );
        petugasLayout.setVerticalGroup(
            petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, 50));

        suplier.setBackground(new java.awt.Color(165, 165, 230));
        suplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suplierMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 32)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(12, 66, 121));
        jLabel18.setText("Supplier");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Suppl (1).png"))); // NOI18N

        javax.swing.GroupLayout suplierLayout = new javax.swing.GroupLayout(suplier);
        suplier.setLayout(suplierLayout);
        suplierLayout.setHorizontalGroup(
            suplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suplierLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        suplierLayout.setVerticalGroup(
            suplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(suplierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25))
        );

        jPanel1.add(suplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 150, 50));

        logout.setBackground(new java.awt.Color(165, 165, 230));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 32)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(12, 66, 121));
        jLabel19.setText("Logout");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Keluarr (1).png"))); // NOI18N

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 690));

        jPanel2.setBackground(new java.awt.Color(71, 116, 234));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel1.setText("Home");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(jLabel1)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 960, 40));

        beli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Butoon.png"))); // NOI18N
        beli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beliMouseClicked(evt);
            }
        });
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Butoon2.png"))); // NOI18N
        jual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jualMouseClicked(evt);
            }
        });
        getContentPane().add(jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        pengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Butoon3.png"))); // NOI18N
        pengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengeluaranMouseClicked(evt);
            }
        });
        getContentPane().add(pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel8.setText("Menu Barang");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel9.setText("Menu Transaksi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        lpbeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Butoon4.png"))); // NOI18N
        lpbeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpbeliMouseClicked(evt);
            }
        });
        getContentPane().add(lpbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        dtbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Butoon6.png"))); // NOI18N
        dtbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtbarangMouseClicked(evt);
            }
        });
        getContentPane().add(dtbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        lpjual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Butoon5.png"))); // NOI18N
        lpjual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpjualMouseClicked(evt);
            }
        });
        getContentPane().add(lpjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel13.setText("Menu Laporan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        promo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Butoon7.png"))); // NOI18N
        promo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                promoMouseClicked(evt);
            }
        });
        getContentPane().add(promo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        retur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Butoon8.png"))); // NOI18N
        retur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returMouseClicked(evt);
            }
        });
        getContentPane().add(retur, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        lpkluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Laporan pengeluaran (1).png"))); // NOI18N
        lpkluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpkluarMouseClicked(evt);
            }
        });
        getContentPane().add(lpkluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beliMouseClicked
this.setVisible(false);
new Transaksi_Beli().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_beliMouseClicked

    private void jualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jualMouseClicked
this.setVisible(false);
new Transaksi_Jual().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jualMouseClicked

    private void pengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengeluaranMouseClicked
this.setVisible(false);
new Pengeluaran().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_pengeluaranMouseClicked

    private void dtbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtbarangMouseClicked
this.setVisible(false);
new Barang().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_dtbarangMouseClicked

    private void promoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promoMouseClicked
this.setVisible(false);
new Promo().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_promoMouseClicked

    private void returMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returMouseClicked
this.setVisible(false);
new Retur().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_returMouseClicked

    private void lpbeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpbeliMouseClicked
this.setVisible(false);
new Laporan_Beli().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_lpbeliMouseClicked

    private void lpjualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpjualMouseClicked
this.setVisible(false);
new Laporan_Jual().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_lpjualMouseClicked

    private void lpkluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpkluarMouseClicked
this.setVisible(false);
new Laporan_Pengeluaran().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_lpkluarMouseClicked

    private void homeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeeMouseClicked
this.setVisible(false);
new Dashboard().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_homeeMouseClicked

    private void petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasMouseClicked
this.setVisible(false);
new Petugas().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_petugasMouseClicked

    private void suplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suplierMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suplierMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
this.setVisible(false);
new Login().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b;
    public static final javax.swing.JLabel beli = new javax.swing.JLabel();
    public static final javax.swing.JLabel dtbarang = new javax.swing.JLabel();
    private javax.swing.JLabel home;
    public static final javax.swing.JPanel homee = new javax.swing.JPanel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static final javax.swing.JPanel jPanel7 = new javax.swing.JPanel();
    public static final javax.swing.JLabel jual = new javax.swing.JLabel();
    public static final javax.swing.JPanel logout = new javax.swing.JPanel();
    public static final javax.swing.JLabel lpbeli = new javax.swing.JLabel();
    public static final javax.swing.JLabel lpjual = new javax.swing.JLabel();
    public static final javax.swing.JLabel lpkluar = new javax.swing.JLabel();
    public static final javax.swing.JLabel pengeluaran = new javax.swing.JLabel();
    public static final javax.swing.JPanel petugas = new javax.swing.JPanel();
    public static final javax.swing.JLabel promo = new javax.swing.JLabel();
    public static final javax.swing.JLabel retur = new javax.swing.JLabel();
    public static final javax.swing.JPanel suplier = new javax.swing.JPanel();
    // End of variables declaration//GEN-END:variables
}
