/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_s2_3;

import New_Desain.*;
import project_s2_3.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static New_Desain.Home.beli;
import static New_Desain.Home.jual;
import static New_Desain.Home.pengeluaran;
import static New_Desain.Home.barang;
import static New_Desain.Home.promo;
import static New_Desain.Home.retur;
import static New_Desain.Home.lpbeli;
import static New_Desain.Home.lpjual;
//import static New_Desain.Menu.lpkluar;
import static New_Desain.Home.home;
import static New_Desain.Home.petugas;
import static New_Desain.Home.suplier;
import static New_Desain.Home.logout;
import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class Login1 extends javax.swing.JFrame {
    Connection con = null;
PreparedStatement pst =null;
ResultSet rs = null;
Home b;

    /**
     * Creates new form Login
     */
    public Login1() {
        initComponents();
        
        b = new Home();
        b.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ptgs = new javax.swing.JComboBox<>();
        ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 38, 83));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(153, 153, 255));
        login.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SKP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sistem Kasir Pintar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 290, 40));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Petugas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Petugas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        Ptgs.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        Ptgs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kasir", "Admin" }));
        jPanel1.add(Ptgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 100, 30));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 590, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baru/Loginnnnn.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try{
            String query = "SELECT * FROM `petugas` WHERE Id_Petugas=? and Password=? and Jabatan=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/new_skp_project", "root","");
            pst = con.prepareStatement(query);
            pst.setString(1, ID.getText());
            pst.setString(2, password.getText());
            pst.setString(3, String.valueOf(Ptgs.getSelectedItem()));
            rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "username dan password anda benar anda login sebagai "+rs.getString("Jabatan"));
                if(Ptgs.getSelectedIndex()==0){
                    b.setVisible(true);
                    Kasir a = new Kasir();
                    home.setEnabled(true);
                    suplier.setEnabled(false);
                    petugas.setEnabled(false);
                    logout.setEnabled(true);
                    beli.setEnabled(true);
                    jual.setEnabled(true);
                    pengeluaran.setEnabled(false);
                    lpbeli.setEnabled(false);
                    lpjual.setEnabled(false);
                    barang.setEnabled(false);
                    promo.setEnabled(false);
                    retur.setEnabled(true);
                    //                lpkluar.setEnabled(false);

                    //                    //nama.setText(rs.getString(2));
                    //                    Blob gambar =(com.mysql.jdbc.Blob)rs.getBlob("Foto");
                    //                    int ukuran = (int)(gambar.length());
                    //                    ImageIcon tampil = new ImageIcon(gambar.getBytes(1, ukuran));
                    //                    foto.setIcon(tampil);

                }else{
                    b.setVisible(true);
                    home.setEnabled(true);
                    suplier.setEnabled(true);
                    petugas.setEnabled(true);
                    logout.setEnabled(true);
                    beli.setEnabled(false);
                    jual.setEnabled(false);
                    pengeluaran.setEnabled(false);
                    lpbeli.setEnabled(true);
                    lpjual.setEnabled(true);
                    barang.setEnabled(true);
                    promo.setEnabled(true);
                    retur.setEnabled(false);
                    //                lpkluar.setEnabled(true);
                    //nama.setText(rs.getString(2));
                    //                    Blob gambar =(com.mysql.jdbc.Blob)rs.getBlob("Foto");
                    //                    int ukuran = (int)(gambar.length());
                    //                    ImageIcon tampil = new ImageIcon(gambar.getBytes(1, ukuran));
                    //                    foto.setIcon(tampil);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Data yang anda masukkan salah, silahkan coba kembali");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JComboBox<String> Ptgs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables

    private static class Kasir {

        public Kasir() {
        }
    }
}
